version: '3'
services: 
  postgres:
    image: 'postgres:latest'

  redis:
    image: 'redis:latest'
  
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports: 
      - '8099:80'
  
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes: 
      - /app/fibo-server/node_modules
      - ./server:/app/fibo-server
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgre_password
      - PGPORT=5432
  
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes: 
      - /app/fibo-client/node_modules
      - ./client:/app/fibo-client

  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes: 
      - /app/fibo-worker/node_modules
      - ./worker:/app/fibo-worker